// packages/nuxt/src/runtime/components/Blocks.vue
<script setup lang="ts">
import { fieldAttribute, listAttribute } from '@manablox/live-preview';
import {
  BLOCK_CLASS,
  BLOCK_GRID_CSS,
  type Block,
  type BlockGridSettings,
  blockLayoutStyle,
  blocksGridStyle,
  blocksOf,
  columnsUsedBy,
  GRID_CLASS,
  gridOf,
  pascalName,
  uniformGrid,
} from '@manablox/public-sdk';
import { type Component, computed, resolveComponent } from 'vue';

/**
 * Renders blocks by type convention (`teaser` renders `<BlockTeaser>`), tagged for the visual
 * editor. Takes a `blocks` field value, `{ grid, blocks }`.
 */
const props = withDefaults(
  defineProps<{
    blocks: { grid?: BlockGridSettings | null; blocks: Block[] } | null | undefined;
    field?: string;
    prefix?: string;
    /** Overrides the grid the value carries. */
    grid?: BlockGridSettings | null;
    /** Any CSS length. */
    gap?: string | undefined;
  }>(),
  { field: 'components', prefix: 'Block', grid: null, gap: undefined },
);

const items = computed(() => blocksOf(props.blocks));

const resolved = computed(
  () =>
    props.grid ??
    gridOf(props.blocks) ??
    uniformGrid(columnsUsedBy(items.value.map((block) => block.layout ?? null))),
);
const gridStyle = computed(() =>
  blocksGridStyle(resolved.value, props.gap ? { gap: props.gap } : {}),
);

/** GraphQL names the type in `typeName`, REST in `type`. */
function componentFor(block: Block): Component | string {
  const name = typeof block.typeName === 'string' ? block.typeName : block.type;
  return resolveComponent(pascalName(name ?? '', props.prefix));
}

const stylesheet = BLOCK_GRID_CSS;
</script>

<template>
  <div :class="GRID_CLASS" v-bind="listAttribute([field])" :style="gridStyle">
    <component :is="'style'">{{ stylesheet }}</component>
    <component
      :is="componentFor(block)"
      v-for="(block, index) in items"
      :key="block.blockId"
      :class="BLOCK_CLASS"
      v-bind="{ ...block, ...fieldAttribute([field, index]) }"
      :style="blockLayoutStyle(block.layout ?? null, resolved) || undefined"
    />
  </div>
</template>

// packages/cli/templates/react-ssr/src/components/Blocks.tsx
import { listAttribute } from '@manablox/live-preview';
import {
  BLOCK_CLASS,
  type Block,
  blockLayoutStyle,
  blocksGridStyle,
  columnsUsedBy,
  GRID_CLASS,
  gridOf,
  uniformGrid,
} from '@manablox/public-sdk';
import { blockRenderers } from './blocks/index.js';

/**
 * A blocks field, each block through the registry in `./blocks/index.ts`. The list is
 * tagged for the visual editor, so it can offer "add a block" while it is empty, and
 * laid out as a grid when the admin placed the blocks on one: each block's layout
 * becomes the custom properties the SDK's stylesheet reads.
 *
 * `path` is where the field sits: `['components']` on a page, deeper inside a block.
 */
export function Blocks({
  blocks,
  path,
  value,
}: {
  blocks: Block[];
  path: (string | number)[];
  value?: unknown;
}) {
  const grid = gridOf(value) ?? uniformGrid(columnsUsedBy(blocks));

  return (
    <div className={GRID_CLASS} {...listAttribute(path)} style={cssText(blocksGridStyle(grid))}>
      {blocks.map((block, index) => {
        const Renderer = blockRenderers[block.type];
        const style = cssText(blockLayoutStyle(block, grid));
        return Renderer ? (
          <div key={block.blockId} className={BLOCK_CLASS} style={style}>
            <Renderer block={block} path={[...path, index]} />
          </div>
        ) : (
          // An unknown block type renders a visible note rather than vanishing.
          <div key={block.blockId} className={`${BLOCK_CLASS} unknown`} style={style}>
            No renderer for block type "{block.type}".
          </div>
        );
      })}
    </div>
  );
}

/**
 * The SDK hands out a CSS declaration list, and React's `style` takes an object. The
 * declarations are custom properties, which React passes through untouched.
 */
function cssText(text: string): Record<string, string> {
  const style: Record<string, string> = {};
  for (const declaration of text.split(';')) {
    const [property, ...rest] = declaration.split(':');
    if (!property || rest.length === 0) continue;
    style[property.trim()] = rest.join(':').trim();
  }
  return style;
}
